-- MySQL Script generated by MySQL Workbench
-- Sat Jun 17 02:54:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_prsp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_prsp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_prsp` DEFAULT CHARACTER SET utf8 ;
USE `bd_prsp` ;

-- -----------------------------------------------------
-- Table `bd_prsp`.`utentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`utentes` (
  `idutente` INT NOT NULL AUTO_INCREMENT,
  `utenteNome` VARCHAR(200) NOT NULL,
  `utentTelefone` VARCHAR(45) NOT NULL,
  `utenteEmail` VARCHAR(100) NOT NULL,
  `utenteSenha` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idutente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`foto_gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`foto_gestor` (
  `idfoto_gestor` INT NOT NULL AUTO_INCREMENT,
  `gestorFoto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfoto_gestor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`gestores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`gestores` (
  `idgestor` INT NOT NULL AUTO_INCREMENT,
  `gestorNome` VARCHAR(200) NOT NULL,
  `gestorEmail` VARCHAR(45) NOT NULL,
  `gestorTelefone` VARCHAR(45) NOT NULL,
  `gestorBIDocs` VARCHAR(100) NOT NULL,
  `gestorDocs` VARCHAR(45) NOT NULL,
  `idFotoGestor` INT NOT NULL,
  `gestorSenha` VARCHAR(200) NOT NULL,
  `gestorDataRegistro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgestor`),
  INDEX `fk_gestores_foto_gestor1_idx` (`idFotoGestor` ASC),
  CONSTRAINT `fk_gestores_foto_gestor1`
    FOREIGN KEY (`idFotoGestor`)
    REFERENCES `bd_prsp`.`foto_gestor` (`idfoto_gestor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`foto_adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`foto_adm` (
  `idfoto_adm` INT NOT NULL AUTO_INCREMENT,
  `admFoto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfoto_adm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`nivel_acesso_adm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`nivel_acesso_adm` (
  `idnivel_acesso_adm` INT NOT NULL AUTO_INCREMENT,
  `numNivelAcesso` ENUM('1', '2', '3') NOT NULL DEFAULT '3',
  PRIMARY KEY (`idnivel_acesso_adm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`administradores` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT,
  `idNivelAcesso` INT NOT NULL,
  `admNome` VARCHAR(200) NOT NULL,
  `admTelefone` VARCHAR(45) NOT NULL,
  `admEmail` VARCHAR(200) NOT NULL,
  `admSenha` VARCHAR(200) NOT NULL,
  `idFotoAdm` INT NOT NULL,
  PRIMARY KEY (`idadministrador`),
  INDEX `fk_administradores_foto_adm1_idx` (`idFotoAdm` ASC),
  INDEX `fk_administradores_nivel_acesso_adm1_idx` (`idNivelAcesso` ASC),
  CONSTRAINT `fk_administradores_foto_adm1`
    FOREIGN KEY (`idFotoAdm`)
    REFERENCES `bd_prsp`.`foto_adm` (`idfoto_adm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_administradores_nivel_acesso_adm1`
    FOREIGN KEY (`idNivelAcesso`)
    REFERENCES `bd_prsp`.`nivel_acesso_adm` (`idnivel_acesso_adm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`estado_conta_gestores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`estado_conta_gestores` (
  `idestado_conta_gestor` INT NOT NULL AUTO_INCREMENT,
  `estadoContaGestor` ENUM('0', '1') NOT NULL DEFAULT '0',
  `idContaGestor` INT NOT NULL,
  `idContaAdm` INT NOT NULL,
  `estadoDataMudanca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado_conta_gestor`),
  INDEX `fk_estado_conta_gestores_gestores_idx` (`idContaGestor` ASC),
  INDEX `fk_estado_conta_gestores_administradores1_idx` (`idContaAdm` ASC),
  CONSTRAINT `fk_estado_conta_gestores_gestores`
    FOREIGN KEY (`idContaGestor`)
    REFERENCES `bd_prsp`.`gestores` (`idgestor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estado_conta_gestores_administradores1`
    FOREIGN KEY (`idContaAdm`)
    REFERENCES `bd_prsp`.`administradores` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`estado_conta_utentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`estado_conta_utentes` (
  `idestado_conta_utente` INT NOT NULL AUTO_INCREMENT,
  `estadoContaUtente` ENUM('0', '1') NOT NULL DEFAULT '0',
  `idContaUtente` INT NOT NULL,
  `idContaAdm` INT NOT NULL,
  `estadoContaDataAprovacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado_conta_utente`),
  INDEX `fk_estado_conta_utentes_utentes1_idx` (`idContaUtente` ASC),
  INDEX `fk_estado_conta_utentes_administradores1_idx` (`idContaAdm` ASC),
  CONSTRAINT `fk_estado_conta_utentes_utentes1`
    FOREIGN KEY (`idContaUtente`)
    REFERENCES `bd_prsp`.`utentes` (`idutente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estado_conta_utentes_administradores1`
    FOREIGN KEY (`idContaAdm`)
    REFERENCES `bd_prsp`.`administradores` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`estado_posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`estado_posto` (
  `idestado_posto` INT NOT NULL AUTO_INCREMENT,
  `estadoPosto` ENUM('0', '1') NOT NULL DEFAULT '0',
  `idContaAdm` INT NOT NULL,
  `postoDataAtivacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado_posto`),
  INDEX `fk_estado_posto_administradores1_idx` (`idContaAdm` ASC),
  CONSTRAINT `fk_estado_posto_administradores1`
    FOREIGN KEY (`idContaAdm`)
    REFERENCES `bd_prsp`.`administradores` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`categoria_posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`categoria_posto` (
  `idcategoria_posto` INT NOT NULL AUTO_INCREMENT,
  `categoriaPostoDesignacao` VARCHAR(45) NOT NULL DEFAULT 'Notário',
  PRIMARY KEY (`idcategoria_posto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`postos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`postos` (
  `idposto` INT NOT NULL AUTO_INCREMENT,
  `postoDesignacao` VARCHAR(200) NOT NULL,
  `idContaGestor` INT NOT NULL,
  `postoLinkLocalizacao` VARCHAR(500) NOT NULL,
  `idEstadoconta` INT NOT NULL,
  `idCategoriaPosto` INT NOT NULL,
  `postoDataRegistro` VARCHAR(45) NOT NULL,
  `postoemail` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idposto`),
  INDEX `fk_postos_gestores1_idx` (`idContaGestor` ASC),
  INDEX `fk_postos_estado_posto1_idx` (`idEstadoconta` ASC),
  INDEX `fk_postos_categoria_posto1_idx` (`idCategoriaPosto` ASC),
  CONSTRAINT `fk_postos_gestores1`
    FOREIGN KEY (`idContaGestor`)
    REFERENCES `bd_prsp`.`gestores` (`idgestor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postos_estado_posto1`
    FOREIGN KEY (`idEstadoconta`)
    REFERENCES `bd_prsp`.`estado_posto` (`idestado_posto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postos_categoria_posto1`
    FOREIGN KEY (`idCategoriaPosto`)
    REFERENCES `bd_prsp`.`categoria_posto` (`idcategoria_posto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`foto_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`foto_documento` (
  `idfoto_documento` INT NOT NULL AUTO_INCREMENT,
  `fotoDocumento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfoto_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`documentos` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `idPosto` INT NOT NULL,
  `documentoDesignacao` VARCHAR(100) NOT NULL,
  `documentoRequisitos` LONGTEXT NOT NULL,
  `documentoPreco` VARCHAR(45) NOT NULL,
  `documentoTempoDuracao` VARCHAR(45) NOT NULL,
  `idFotoDocumento` INT NOT NULL,
  `documentoDataValidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddocumento`),
  INDEX `fk_documentos_postos1_idx` (`idPosto` ASC),
  INDEX `fk_documentos_foto_documento1_idx` (`idFotoDocumento` ASC),
  CONSTRAINT `fk_documentos_postos1`
    FOREIGN KEY (`idPosto`)
    REFERENCES `bd_prsp`.`postos` (`idposto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_foto_documento1`
    FOREIGN KEY (`idFotoDocumento`)
    REFERENCES `bd_prsp`.`foto_documento` (`idfoto_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`estado_solicitacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`estado_solicitacao` (
  `idestado_solicitacao` INT NOT NULL AUTO_INCREMENT,
  `estadoSolicitacao` ENUM('pendente', 'aprovado', 'recusado') NOT NULL DEFAULT 'pendente',
  PRIMARY KEY (`idestado_solicitacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`relevancia_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`relevancia_documento` (
  `idrelevancia_documento` INT NOT NULL AUTO_INCREMENT,
  `estadoRelevancia` ENUM('Normal', 'Urgente') NOT NULL DEFAULT 'Normal',
  PRIMARY KEY (`idrelevancia_documento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`solicitacao_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`solicitacao_reserva` (
  `idsolicitacao_reserva` INT NOT NULL AUTO_INCREMENT,
  `idContaUtente` INT NOT NULL,
  `idDocumento` INT NOT NULL,
  `idPosto` INT NOT NULL,
  `idEstadoSolicitacao` INT NOT NULL,
  `idRelevancia` INT NOT NULL,
  `solicitacaoReservaData` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsolicitacao_reserva`),
  INDEX `fk_solicitacao_reserva_utentes1_idx` (`idContaUtente` ASC),
  INDEX `fk_solicitacao_reserva_documentos1_idx` (`idDocumento` ASC),
  INDEX `fk_solicitacao_reserva_postos1_idx` (`idPosto` ASC),
  INDEX `fk_solicitacao_reserva_estado_solicitacao1_idx` (`idEstadoSolicitacao` ASC),
  INDEX `fk_solicitacao_reserva_relevancia_documento1_idx` (`idRelevancia` ASC),
  CONSTRAINT `fk_solicitacao_reserva_utentes1`
    FOREIGN KEY (`idContaUtente`)
    REFERENCES `bd_prsp`.`utentes` (`idutente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_reserva_documentos1`
    FOREIGN KEY (`idDocumento`)
    REFERENCES `bd_prsp`.`documentos` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_reserva_postos1`
    FOREIGN KEY (`idPosto`)
    REFERENCES `bd_prsp`.`postos` (`idposto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_reserva_estado_solicitacao1`
    FOREIGN KEY (`idEstadoSolicitacao`)
    REFERENCES `bd_prsp`.`estado_solicitacao` (`idestado_solicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitacao_reserva_relevancia_documento1`
    FOREIGN KEY (`idRelevancia`)
    REFERENCES `bd_prsp`.`relevancia_documento` (`idrelevancia_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`comprovativo_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`comprovativo_reserva` (
  `idcomprovativo_reserva` INT NOT NULL AUTO_INCREMENT,
  `codigoReferencia` VARCHAR(45) NOT NULL,
  `idContaUtente` INT NOT NULL,
  `idReserva` INT NOT NULL,
  `comprovativoData` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcomprovativo_reserva`),
  INDEX `fk_comprovativo_reserva_utentes1_idx` (`idContaUtente` ASC),
  INDEX `fk_comprovativo_reserva_solicitacao_reserva1_idx` (`idReserva` ASC),
  CONSTRAINT `fk_comprovativo_reserva_utentes1`
    FOREIGN KEY (`idContaUtente`)
    REFERENCES `bd_prsp`.`utentes` (`idutente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comprovativo_reserva_solicitacao_reserva1`
    FOREIGN KEY (`idReserva`)
    REFERENCES `bd_prsp`.`solicitacao_reserva` (`idsolicitacao_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_prsp`.`tokens_posto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_prsp`.`tokens_posto` (
  `idtokens_posto` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(45) NOT NULL,
  `idPosto` INT NOT NULL,
  PRIMARY KEY (`idtokens_posto`),
  INDEX `fk_tokens_posto_postos1_idx` (`idPosto` ASC),
  CONSTRAINT `fk_tokens_posto_postos1`
    FOREIGN KEY (`idPosto`)
    REFERENCES `bd_prsp`.`postos` (`idposto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
